package main.view;

//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import main.Controller;

import java.awt.*;
import java.util.LinkedList;
import java.util.List;
import javax.swing.*;

public class GUI extends JPanel {
    private JLabel nameLbl;
    private JLabel destinationLbl;
    private JLabel dateLbl;
    private JLabel hotelLbl;
    private JLabel roomTypeLbl;
    private JLabel jcomp6;
    private JLabel amountLbl;
    private JLabel tranferLbl;
    private JLabel flightOutLbl;
    private JLabel golfAmountLbl;
    private JTextField name;
    private JTextField destination;
    private JComboBox arrivalDate;
    private JComboBox arrivalMonth;
    private JComboBox departureDate;
    private JComboBox departureMonth;
    private JLabel jcomp17;
    private JTextField hotel;
    private JTextField roomType;
    private JTextField boarding;
    private JComboBox amount;
    private JTextField transfer;
    private JTextField golfAmount;
    private JTextField flightOut;
    private JComboBox flightOutDate;
    private JComboBox flightOutMonth;
    private JLabel flightInLbl;
    private JTextField flightIn;
    private JComboBox flightInDate;
    private JComboBox flightInMonth;
    private JButton pdfButton;
    private JList golfTimesList;
    private JComboBox startHour;
    private JComboBox startMinute;
    private JLabel jcomp35;
    private JComboBox untilHour;
    private JComboBox untilMinute;
    private JButton addTime;
    private JButton addGolf;
    private JTextField golfName;
    private JLabel golfLbl;
    private JLabel golfTimeLbl;
    private JButton upButton;
    private JButton downButton;
    private JButton removeButton;
    private JTextField departurePort;
    private JTextField arrivalPort;
    private JComboBox flightOutDHour;
    private JComboBox flightOutDMinute;
    private JLabel jcomp50;
    private JComboBox flightOutAHour;
    private JComboBox flightOutAMinute;
    private JComboBox flightInDHour;
    private JComboBox flightInDMinute;
    private JLabel jcomp55;
    private JComboBox flightInAHour;
    private JComboBox flightInAMinute;
    private JTextField flightOutLocation;
    private JTextField flightInLocation;
    private JComboBox startDate;
    private JComboBox startMonth;
    private JLabel jcomp62;
    private JTextField price;
    private DefaultListModel<String> model;
    private static Controller controller;

    public GUI() {
        //construct preComponents
        model = new DefaultListModel<>();

        String[] arrivalDateItems = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"};
        String[] arrivalMonthItems = {"Jan", "Feb", "Mar", "Apr", "Maj", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dec"};
        String[] departureDateItems = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"};
        String[] departureMonthItems = {"Jan", "Feb", "Mar", "Apr", "Maj", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dec"};
        String[] amountItems = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"};
        String[] flightOutDateItems = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"};
        String[] flightOutMonthItems = {"Jan", "Feb", "Mar", "Apr", "Maj", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dec"};
        String[] flightInDateItems = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"};
        String[] flightInMonthItems = {"Jan", "Feb", "Mar", "Apr", "Maj", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dec"};
        String[] golfTimesListItems = {};
        String[] startHourItems = {"00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"};
        String[] startMinuteItems = {"00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55"};
        String[] untilHourItems = {"00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"};
        String[] untilMinuteItems = {"00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55"};
        String[] flightOutDHourItems = {"00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"};
        String[] flightOutDMinuteItems = {"00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55"};
        String[] flightOutAHourItems = {"00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"};
        String[] flightOutAMinuteItems = {"00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55"};
        String[] flightInDHourItems = {"00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"};
        String[] flightInDMinuteItems = {"00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55"};
        String[] flightInAHourItems = {"00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"};
        String[] flightInAMinuteItems = {"00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55"};
        String[] startDateItems = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"};
        String[] startMonthItems = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"};

        //construct components
        nameLbl = new JLabel ("Resen\u00E4r:");
        nameLbl.setFocusable(false);
        destinationLbl = new JLabel ("Resm\u00E5l:");
        destinationLbl.setFocusable(false);
        dateLbl = new JLabel ("Datum:");
        dateLbl.setFocusable(false);
        hotelLbl = new JLabel ("Hotell:");
        hotelLbl.setFocusable(false);
        roomTypeLbl = new JLabel ("Rumstyp:");
        roomTypeLbl.setFocusable(false);
        jcomp6 = new JLabel ("Pension:");
        jcomp6.setFocusable(false);
        amountLbl = new JLabel ("Antal:");
        amountLbl.setFocusable(false);
        tranferLbl = new JLabel ("Transfer:");
        tranferLbl.setFocusable(false);
        flightOutLbl = new JLabel ("Flyg ut:");
        flightOutLbl.setFocusable(false);
        golfAmountLbl = new JLabel ("Golf:");
        golfAmountLbl.setFocusable(false);
        name = new JTextField (5);
        destination = new JTextField (5);
        arrivalDate = new JComboBox (arrivalDateItems);
        arrivalDate.setFocusable(false);
        arrivalMonth = new JComboBox (arrivalMonthItems);
        arrivalMonth.setFocusable(false);
        departureDate = new JComboBox (departureDateItems);
        departureDate.setFocusable(false);
        departureMonth = new JComboBox (departureMonthItems);
        departureMonth.setFocusable(false);
        jcomp17 = new JLabel ("    -");
        jcomp17.setFocusable(false);
        hotel = new JTextField (5);
        roomType = new JTextField (5);
        boarding = new JTextField (5);
        amount = new JComboBox (amountItems);
        amount.setFocusable(false);
        transfer = new JTextField (5);
        golfAmount = new JTextField (5);
        flightOut = new JTextField (5);
        flightOutDate = new JComboBox (flightOutDateItems);
        flightOutDate.setFocusable(false);
        flightOutMonth = new JComboBox (flightOutMonthItems);
        flightOutMonth.setFocusable(false);
        flightInLbl = new JLabel ("Flyg in:");
        flightInLbl.setFocusable(false);
        flightIn = new JTextField (5);
        flightInDate = new JComboBox (flightInDateItems);
        flightInDate.setFocusable(false);
        flightInMonth = new JComboBox (flightInMonthItems);
        flightInMonth.setFocusable(false);
        pdfButton = new JButton ("Skapa PDF");
        pdfButton.setFocusable(false);
        pdfButton.addActionListener(l->createPDF());
        golfTimesList = new JList (golfTimesListItems);
        golfTimesList.setFocusable(false);
        startHour = new JComboBox (startHourItems);
        startHour.setFocusable(false);
        startMinute = new JComboBox (startMinuteItems);
        startMinute.setFocusable(false);
        jcomp35 = new JLabel ("    -");
        jcomp35.setFocusable(false);
        untilHour = new JComboBox (untilHourItems);
        untilHour.setFocusable(false);
        untilMinute = new JComboBox (untilMinuteItems);
        untilMinute.setFocusable(false);
        addTime = new JButton ("L\u00E4gg till");
        addTime.setFocusable(false);
        addTime.addActionListener(l->addToList(true));
        addGolf = new JButton ("L\u00E4gg till");
        addGolf.setFocusable(false);
        addGolf.addActionListener(l->addToList(false));
        golfName = new JTextField (5);
        //golfName.setFocusable(false);
        golfLbl = new JLabel ("Golfbana:");
        golfLbl.setFocusable(false);
        golfTimeLbl = new JLabel ("Tid:");
        golfTimeLbl.setFocusable(false);
        upButton = new JButton ("\u2191");
        upButton.setFocusable(false);
        upButton.addActionListener(l->upList());
        downButton = new JButton ("\u2193");
        downButton.setFocusable(false);
        downButton.addActionListener(l->downList());
        removeButton = new JButton ("-");
        removeButton.setFocusable(false);
        removeButton.addActionListener(l->removeFromList());
        departurePort = new JTextField (5);
        arrivalPort = new JTextField (5);
        flightOutDHour = new JComboBox (flightOutDHourItems);
        flightOutDHour.setFocusable(false);
        flightOutDMinute = new JComboBox (flightOutDMinuteItems);
        flightOutDMinute.setFocusable(false);
        jcomp50 = new JLabel ("    -");
        jcomp50.setFocusable(false);
        flightOutAHour = new JComboBox (flightOutAHourItems);
        flightOutAMinute = new JComboBox (flightOutAMinuteItems);
        flightInDHour = new JComboBox (flightInDHourItems);
        flightInDMinute = new JComboBox (flightInDMinuteItems);
        jcomp55 = new JLabel ("    -");
        flightInAHour = new JComboBox (flightInAHourItems);
        flightInAMinute = new JComboBox (flightInAMinuteItems);
        flightOutLocation = new JTextField (5);
        flightInLocation = new JTextField (5);
        startDate = new JComboBox (startDateItems);
        startMonth = new JComboBox (startMonthItems);
        jcomp62 = new JLabel ("Pris:");
        price = new JTextField (5);

        //set components properties
        flightOut.setToolTipText ("SK3242");
        flightIn.setToolTipText ("SK3242");
        departurePort.setToolTipText ("ARN");
        arrivalPort.setToolTipText ("ARN");

        //adjust size and set layout
        setPreferredSize (new Dimension (727, 366));
        setLayout (null);

        //add components
        add (nameLbl);
        add (destinationLbl);
        add (dateLbl);
        add (hotelLbl);
        add (roomTypeLbl);
        add (jcomp6);
        add (amountLbl);
        add (tranferLbl);
        add (flightOutLbl);
        add (golfAmountLbl);
        add (name);
        add (destination);
        add (arrivalDate);
        add (arrivalMonth);
        add (departureDate);
        add (departureMonth);
        add (jcomp17);
        add (hotel);
        add (roomType);
        add (boarding);
        add (amount);
        add (transfer);
        add (golfAmount);
        add (flightOut);
        add (flightOutDate);
        add (flightOutMonth);
        add (flightInLbl);
        add (flightIn);
        add (flightInDate);
        add (flightInMonth);
        add (pdfButton);
        add (golfTimesList);
        add (startHour);
        add (startMinute);
        add (jcomp35);
        add (untilHour);
        add (untilMinute);
        add (addTime);
        add (addGolf);
        add (golfName);
        add (golfLbl);
        add (golfTimeLbl);
        add (upButton);
        add (downButton);
        add (removeButton);
        add (departurePort);
        add (arrivalPort);
        add (flightOutDHour);
        add (flightOutDMinute);
        add (jcomp50);
        add (flightOutAHour);
        add (flightOutAMinute);
        add (flightInDHour);
        add (flightInDMinute);
        add (jcomp55);
        add (flightInAHour);
        add (flightInAMinute);
        add (flightOutLocation);
        add (flightInLocation);
        add (startDate);
        add (startMonth);
        add (jcomp62);
        add (price);

        //set component bounds (only needed by Absolute Positioning)
        nameLbl.setBounds (15, 10, 70, 20);
        destinationLbl.setBounds (15, 35, 70, 20);
        dateLbl.setBounds (15, 60, 70, 20);
        hotelLbl.setBounds (15, 85, 70, 20);
        roomTypeLbl.setBounds (15, 110, 70, 20);
        jcomp6.setBounds (15, 135, 70, 20);
        amountLbl.setBounds (15, 160, 70, 20);
        tranferLbl.setBounds (15, 185, 70, 20);
        flightOutLbl.setBounds (15, 255, 70, 20);
        golfAmountLbl.setBounds (15, 210, 70, 20);
        name.setBounds (85, 10, 230, 20);
        destination.setBounds (85, 35, 230, 20);
        arrivalDate.setBounds (85, 60, 45, 20);
        arrivalMonth.setBounds (135, 60, 50, 20);
        departureDate.setBounds (215, 60, 45, 20);
        departureMonth.setBounds (265, 60, 48, 20);
        jcomp17.setBounds (185, 60, 30, 20);
        hotel.setBounds (85, 85, 230, 20);
        roomType.setBounds (85, 110, 230, 20);
        boarding.setBounds (85, 135, 230, 20);
        amount.setBounds (85, 160, 45, 20);
        transfer.setBounds (85, 185, 230, 20);
        golfAmount.setBounds (85, 210, 230, 20);
        flightOut.setBounds (85, 255, 125, 20);
        flightOutDate.setBounds (215, 255, 45, 20);
        flightOutMonth.setBounds (265, 255, 48, 20);
        flightInLbl.setBounds (15, 305, 70, 20);
        flightIn.setBounds (85, 305, 125, 20);
        flightInDate.setBounds (215, 305, 45, 20);
        flightInMonth.setBounds (265, 305, 48, 20);
        pdfButton.setBounds (565, 305, 145, 45);
        golfTimesList.setBounds (565, 10, 145, 255);
        startHour.setBounds (330, 110, 45, 20);
        startMinute.setBounds (380, 110, 45, 20);
        jcomp35.setBounds (425, 110, 30, 20);
        untilHour.setBounds (455, 110, 45, 20);
        untilMinute.setBounds (505, 110, 45, 20);
        addTime.setBounds (455, 135, 95, 25);
        addGolf.setBounds (455, 60, 95, 25);
        golfName.setBounds (330, 35, 220, 20);
        golfLbl.setBounds (330, 10, 220, 20);
        golfTimeLbl.setBounds (330, 85, 95, 20);
        upButton.setBounds (565, 265, 45, 25);
        downButton.setBounds (615, 265, 45, 25);
        removeButton.setBounds (665, 265, 45, 25);
        departurePort.setBounds (85, 275, 60, 20);
        arrivalPort.setBounds (85, 325, 60, 20);
        flightOutDHour.setBounds (330, 255, 45, 20);
        flightOutDMinute.setBounds (380, 255, 45, 20);
        jcomp50.setBounds (425, 255, 30, 20);
        flightOutAHour.setBounds (455, 255, 45, 20);
        flightOutAMinute.setBounds (505, 255, 45, 20);
        flightInDHour.setBounds (330, 305, 45, 20);
        flightInDMinute.setBounds (380, 305, 45, 20);
        jcomp55.setBounds (425, 305, 30, 20);
        flightInAHour.setBounds (455, 305, 45, 20);
        flightInAMinute.setBounds (505, 305, 45, 20);
        flightOutLocation.setBounds (150, 275, 165, 20);
        flightInLocation.setBounds (150, 325, 165, 20);
        startDate.setBounds (330, 135, 45, 20);
        startMonth.setBounds (380, 135, 45, 20);
        jcomp62.setBounds (330, 185, 85, 20);
        price.setBounds (330, 210, 95, 20);
    }

    public void start (Controller controller) {
        this.controller = controller;
        JFrame frame = new JFrame ("HWG | Skapa offert");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new GUI());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible (true);
    }

    public void addToList(boolean b){
        if(b){
            model.add(model.getSize(), startDate.getSelectedItem() + "/" + startMonth.getSelectedItem() + " " + startHour.getSelectedItem() + ":" + startMinute.getSelectedItem() + "-" + untilHour.getSelectedItem() + ":" + untilMinute.getSelectedItem());
            golfTimesList.setModel(model);
            golfTimesList.updateUI();
        } else {
            if (golfName.getText().length()>3){
                model.add(model.getSize(),golfName.getText());
                golfTimesList.setModel(model);
                golfTimesList.updateUI();
            }
        }
    }

    public void removeFromList(){
        if (!model.isEmpty()) {
            model.remove(golfTimesList.getSelectedIndex());
            golfTimesList.setModel(model);
            golfTimesList.updateUI();
        }
    }

    public void upList() {
        if (!golfTimesList.isSelectionEmpty()) {
            if (golfTimesList.getSelectedIndex() != 0) {
                String temp = model.getElementAt(golfTimesList.getSelectedIndex()-1);
                model.set(golfTimesList.getSelectedIndex()-1,model.getElementAt(golfTimesList.getSelectedIndex()));
                model.set(golfTimesList.getSelectedIndex(),temp);
                golfTimesList.setSelectedIndex(golfTimesList.getSelectedIndex()-1);
            }
        }
    }

    public void downList(){
        if (!golfTimesList.isSelectionEmpty()) {
            if (golfTimesList.getSelectedIndex() != golfTimesList.getModel().getSize()-1) {
                String temp = model.getElementAt(golfTimesList.getSelectedIndex()+1);
                model.set(golfTimesList.getSelectedIndex()+1,model.getElementAt(golfTimesList.getSelectedIndex()));
                model.set(golfTimesList.getSelectedIndex(),temp);
                golfTimesList.setSelectedIndex(golfTimesList.getSelectedIndex()+1);
            }
        }
    }

    public void createPDF() {
        List info = new LinkedList();
        List times = new LinkedList();
        info.add(name.getText());
        info.add(destination.getText());
        info.add(arrivalDate.getSelectedItem() + " " + arrivalMonth.getSelectedItem() + " - " + departureDate.getSelectedItem() + " " + departureMonth.getSelectedItem());
        info.add(hotel.getText());
        info.add(roomType.getText());
        info.add(boarding.getText());
        if (Integer.parseInt(amount.getSelectedItem().toString()) == 1 ) {
            info.add(amount.getSelectedItem() + " person");
        } else {
            info.add(amount.getSelectedItem() + " personer");
        }
        info.add(transfer.getText());
        info.add(golfAmount.getText());
        info.add(flightOutLocation.getText() + " - " + flightInLocation.getText());
        info.add(flightOut.getText() + " " + flightOutDate.getSelectedItem() + " " + flightOutMonth.getSelectedItem() + " " + departurePort.getText() + " " + flightOutDHour.getSelectedItem() + ":" + flightOutDMinute.getSelectedItem() + "-" + flightOutAHour.getSelectedItem() + ":" + flightOutAMinute.getSelectedItem());
        info.add(flightIn.getText() + " " + flightInDate.getSelectedItem() + " " + flightInMonth.getSelectedItem() + " " + departurePort.getText() + " " + flightInDHour.getSelectedItem() + ":" + flightInDMinute.getSelectedItem() + "-" + flightInAHour.getSelectedItem() + ":" + flightInAMinute.getSelectedItem());
        info.add(price.getText());
        if (!model.isEmpty()) {
            for (int i = 0; i < model.size(); i++) {
                times.add(model.getElementAt(i));
            }
        }
        controller.createPDF(info,times);
    }
}

